### ISSUE TITLE
Make Docker image, docker compose for project

### ISSUE THREAD

**Issue by chriszs** [tvkitchen/countertop#54]
#### Describe the solution you'd like
It'd be good if this project had an official Docker image and Docker Compose file for running the project. Dockerization may be a good approach for TV Kitchen, because people will want to run this in varied environments and Docker allows them to do that without additional setup or modification to those environments, making the project easier to run and manage. In the future, these may include Kubernetes or the various AWS services that support containers.

My suggested plan of action would be:

- [ ] Add a Dockerfile
- [ ] Add a Docker build step in Travis
- [ ] Move docker-compose file to project's top level (this is convention), add TV kitchen image to it
- [ ] Switch Kafka start command to do `docker-compose up -d kafka`
- [ ] Document Docker compose option in README
- [ ] Use Travis to push an official image to a TV Kitchen Docker Hub project on commits, version releases

Can do a quick PR with this if we think this is a good plan.

**Comment by chriszs** [comment]
Reframed this to a feature request, though unable to the modify the label.

**Comment by reefdog** [comment]
I'm all for it! Would hitting #29 be a natural fit at the same time?

**Comment by chriszs** [comment]
Looks like it. Docker Compose [has ways to use environment variables](https://docs.docker.com/compose/environment-variables/) and should pull from an `.env` file in the working directory.

**Comment by slifty** [comment]
This issue was created before we moved to the library architecture; now that we have that, the concept of docker containers are more relevant to the recipes and appliances directly.

We may still find that the countertop should have its own docker container, but for now I think we can close this?  (Please feel free to re-open if I'm totally wrong!)
