### ISSUE TITLE
What should the TV Kitchen entry point be?

### ISSUE THREAD

**Issue by slifty** [tvkitchen/countertop#66]
#### What do you want to talk about?

First: @chriszs has started working on a Docker entry point (🎉) over at #54, and we should continue that line of exploration to think a bit about how people are going to run a copy of TV Kitchen.

We should think about what we want to do for the short term, what we want to support for the long term, and what we want to document as the "recommended" way.  Note that we can support more than one deployment technique.

Some options as I see them right now:

1. `git clone` of the `tv-kitchen` repository and following configuration steps.
2. Docker container (e.g. #54) along with configuration steps.
3. A `tvk` command line tool (e.g. `tvk start -c config.json` or whatever).
4. An npm package that people can import into their own code base.

Some of this came up in dialogue around #65, since some of the appliance installation approaches might have relied on a modification of a `package.json` (we are likely NOT going to be following those approaches).

#### Relevant Resources / Research
None for now, though I know there must be a ton out there about this issue.

**Comment by chriszs** [comment]
A couple projects I've done have followed a pattern of script (#1) -> API (#4) -> CLI (#3) -> Docker (#2), where the script is an intermediate stage, later refactored to a CLI sitting on top of an API, installable via `npm` or `npx` and then Dockerized.

**Comment by chriszs** [comment]
An additional consideration: Okay, so you have your daemon. Let's say it has a basic CLI focused on providing file-based configuration. Do you also want a separate configuration CLI that acts as a client once you have a configuration store? Or is that the same CLI?

**Comment by reefdog** [comment]
> 3. A `tvk` command line tool (e.g. `tvk start -c config.json` or whatever).

So presumably what this might do is create and fill a local instance from a template. (Also presumably another way to get that template would be to just clone it directly from GitHub rather than use the CLI tool.) That template would have the main tv-kitchen repo (this one, call it TVK core) as a dependency.

That's kind of the model I was imagining, personally.

**Comment by chriszs** [comment]
Oh, interesting! So like Yeoman?

**Comment by reefdog** [comment]
_Yeoman. Now there's a name I've not heard for a long time. A long time._

But, yes, kind of? Basically the architecture I'm assuming is that the unique footprint of an individual TV Kitchen installation should be as small as possible, mostly config files, with TV Kitchen core, appliances, etc being imported as dependencies.

Custom appliances would either be installed directly from GitHub or via npm, or even defined directly in the installation (`src/appliances`?) if the user didn't want to bother with breaking it out. (We should/would encourage and document, but not require, users posting appliances to GitHub and possibly publishing npm so the rest of the community could benefit.)

**Comment by slifty** [comment]
There's some discussion in #65 that is related to this question (see [this comment](https://github.com/tvkitchen/tv-kitchen/issues/65#issuecomment-644828981)

**Comment by slifty** [comment]
I think this issue is a wrapped up now.  We have recipes that show how to create TVK instances (those recipes could be considered entrypoints, but at the very least they show how the code level entrypoint is the Coutnertop)
