### ISSUE TITLE
Ingest cable channels

### ISSUE THREAD

**Issue by chriszs** [tvkitchen/countertop#78]
#### Is your feature request related to a problem? Please describe.
HDHomeRun will work for over-the-air broadcasts and non-protected cable channels. But what's our story for protected cable channels?

#### Describe the solution you'd like
We should look at the available options for this and maybe have suggested hardware and an ingestion engine to interface with it.

#### Describe alternatives you've considered
Wait for a cable-card HDHomeRun? Rely on Dan's MIT hookup continuing to function?

**Comment by slifty** [comment]
This is going to be a hardware question, so I'll take it on for now.  The intent is that HDHomeRuns will do the trick but the only cable card varieties I've seen can only be bought used.

cc @traceypooh have you seen any good hardware alternatives?
